### ISSUE TITLE
[ToDo] Regression

### ISSUE THREAD

**Issue by khirotaka** [khirotaka/SAnD#1]
ToDo `RegressionModule`

**Comment by amirarjmand93** [comment]
hello dear 
I have tried to pivot to the **regression** model based on your classification network structure. I changed to _modules.RegressionModule_ and some reshaping on the input/target train and test data. the final result that I could get is about **53% accuracy** with at least batch_size=128 and (1024,256,23) tensor size. 
do you think this result is acceptable with the random tensors dataset?

**Comment by khirotaka** [comment]
I don't know. Do your own research.
