### ISSUE TITLE
Improved Documentation (for Regression)

### ISSUE THREAD

**Issue by joelrorseth** [khirotaka/SAnD#4]
Hi, first of all thank you for taking the time to create this implementation. I have yet to find another. I'm using this model for a project, particularly for a regression problem.

I was wondering whether the regression module is fully complete, and if you would be able to add some documentation (how to properly instantiate it, description of each parameter etc)? I see that the core SAnD nn.module hardcodes the `ClassificationModule` instead of the `RegressionModule`, so I am wondering whether the model will work correctly if I simply replace it with `RegressionModule` and provide `output_size` instead of `n_class`?

It would also be great if the README contained a few brief, but complete examples for instantiating a SAnD model (for classification and regression). In its current form, it is unclear how the trainer and model work together, or how one might use the SAnD nn.module with other frameworks to train. Thanks!

**Comment by khirotaka** [comment]
joelrorseth-san.

Thank you for your interest in my project.

First, the `ClassificationModule` and `RegressionModule`. As you said, if you specify the size of the output in the regression in the n_class place, you can get the same behavior should be.

Alternatively, if you want to use the `RegressionModule` as a module of the `SAnD` itself, you can use Try writing a code.

```python
from core.model import SAnD
from core.modules import RegressionModule


class RegSAnD(SAnD):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs):
        d_model = kwargs.get("d_model")
        factor = kwargs.get("factor")
        output_size = kwargs.get("n_class")    # output_size

        self.clf = RegressionModule(d_model, factor, output_size)



model = RegSAnD(
    input_features=..., seq_len=..., n_heads=..., factor=...,
    n_class=..., n_layers=...
)
```

Maybe it works fine. 


About simple usage.

At one point, I had used the `SAnD` and [UCI HAR](https://archive.ics.uci.edu/ml/datasets/human+activity+recognition+using+smartphones) dataset to investigate the classification of daily activities.
I'm going to share the code with you. (Code that was kept completely unappreciated by advising teacher will see the light of day.)

I don't know of any good datasets that are readily available for regression tasks, so I'd be happy to share them with you.

**Comment by joelrorseth** [comment]
Thanks for the quick reply. Glad to hear RegressionModule works as expected.

That would be great if I could get that code from you! I am very much interested to see how your experiment worked out, since my data and use case is very much similar. If you have it, feel free to email me (see my Github profile for email address) or comment with a link. Much appreciated!
