### ISSUE TITLE
How to deal with regression task?

### ISSUE THREAD

**Issue by Answerfxy** [khirotaka/SAnD#8]
Hi Khirotaka,

Thanks for proving the code.
I am a little confused about how to convert the default classification task to the regression one.

As you said in the README file, there are two steps:
Specify the number of output dimensions in num_class.
Inherit class SAnD and overwrite ClassificationModule with RegressionModule.

Am I did correct in the following steps:
1. Cuz it's a regression problem, num_class should be set to 1.
2. Also, I just simply convert ClassificationModule to RegressionModule in the model.py file.

Thanks for your time!

**Comment by khirotaka** [comment]
There is no problem with the procedure you showed.  As a side note, if the output is set to `1`, the information one step ahead should be predicted, so if you want to predict future information (for example, 100 steps ahead), you can set `num_class = 100`.

However, SAnD should have been proposed as a classification model, so you can't tell if regression works until you try it.

**Comment by Answerfxy** [comment]
> There is no problem with the procedure you showed. As a side note, if the output is set to `1`, the information one step ahead should be predicted, so if you want to predict future information (for example, 100 steps ahead), you can set `num_class = 100`.
> 
> However, SAnD should have been proposed as a classification model, so you can't tell if regression works until you try it.

Thanks for the explanation about num_class in regression!
